# Generated by Django 4.2.18 on 2026-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glomar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("virtual", "Virtual"), ("in_person", "In Person")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "—"),
                    ("registered", "Registered"),
                    ("attended", "Attended"),
                    ("no_show", "No-show"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
